name: pandoc

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - Chapter*.md
      - listing.tex
      - .github/workflows/pandoc.yaml

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lpi-japan/server-text:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v3
      - id: list-files
        run: echo "chapter=$(ls -1 Chapter*.md | sort -V | tr '\n' ' ' | sed 's/ $//')" >> "$GITHUB_OUTPUT"
        shell: bash
      - run: pandoc -o guide.pdf -d config.yaml ${{ steps.list-files.outputs.chapter }}
      - uses: actions/upload-artifact@v3
        with:
          name: guide.pdf
          path: guide.pdf
